INSERT INTO candidate_technology (candidate_id, technology_id, level, note) VALUES
  (1, 1, 10, 'Senior dev'),  
  (1, 3, 7, 'Pokrocile znalosti'),
  (1, 4, 6, 'Free time zaliba'),
  (2, 7, 10, 'Frontend buh'),
  (2, 8, 9, 'Typovani neni muj salek kavy'),
  (2, 9, 10, 'Profik'),
  (2, 10, 10, 'Milovnik CSS'),
  (2, 3, 5, 'Chvili delal s Pythonem'),
  (3, 2, 10, 'Kotlin buh'),
  (3, 1, 10, 'Java buh'),
  (4, 3, 10, 'Python je muj matersky jazyk'),
  (4, 15, 9, 'Pracuji s fastapi'),
  (5, 13, 9, 'React je ma laska'),
  (5, 7, 9, 'JavaScript k Reactu'),
  (6, 1, 7, 'Java'),
  (6, 14, 6, 'Spring boot');
